
### root access
GET  http://localhost:8000

### Login api endpoing
POST  http://localhost:8000/api/v1/login
Content-Type: application/json

{
  "email": "test@emai.comd",
  "password": "12346"
}




### Categor Zone ####
### Fetch all category
GET  http://localhost:8000/api/v1/category


### Add a category
POST  http://localhost:8000/api/v1/category
Content-Type: application/json

{"name": "Root Category", "parentCat": 0}

### Delete Categories
Delete  http://localhost:8000/api/v1/category
 
 
### Products APIs
### Add new product
POST  http://localhost:8000/api/v1/product
Content-Type: application/json

{"name": "Root Category", 
"price": 0}